version: '3'
services:

  mysql:
    build: ./mysql
    ports:
      - "13306:3306"
    networks:
      - app-net
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nuxt:
    build: ./app
    container_name: app
    environment:
      NUXT_DATABASE_HOST: mysql
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      mysql:
        condition: service_healthy

networks:
  app-net:
    driver: bridge